/*
** This file and the folder that it is in was generated by the
** Node Package dukeapi found at: https://www.npmjs.com/package/dukeapi
**
** Version: 1.0.0
** Author: David H. Isakson II
** License: MIT
** Github: https://github.com/ikeman32/duke-api-wauth
** Contact: david.isakson.ii@gmail.com
*/
/*
**Contributors:
**Seth Cox
**David Isakson
**April - May 2020
*/

require("dotenv").config();
  const server = require("./api/server.js");

  const port = process.env.PORT;

  server.listen(port, function() {
  console.log(`\n Server is running on localhost:${port} \n`);
  });
