/*
 ** This file and the folder that it is in was generated by the
 ** Node Package dukeapi found at: https://www.npmjs.com/package/dukeapi
 **
 ** Version: 1.0.0
 ** Author: David H. Isakson II
 ** License: MIT
 ** Github: https://github.com/ikeman32/duke-api-wauth
 ** Contact: david.isakson.ii@gmail.com
 */
 /*
 **Contributors:
 **Seth Cox
 **David Isakson
 **April - May 2020
 */
require("dotenv").config();
const router = require("express").Router();
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken"); // installed this
const SALT_ROUNDS = parseInt(process.env.SALT_ROUNDS);
const { userValidationRules, validate } = require("../middleware/validation");

const User = require("../models/auth-model");

//JWT End Points generated by dukeapi
router.post("/register", userValidationRules(), validate, (req, res) => {
  let user = req.body;
  const hash = bcrypt.hashSync(user.password, SALT_ROUNDS); // 2 ^ n
  user.password = hash;

  User.add(user)
    .then((saved) => {
      res.status(201).json(saved);
    })
    .catch((error) => {
      res.status(500).json(error);
    });
});

router.post("/login", userValidationRules(), validate, (req, res) => {
  let { email, password } = req.body;


  User.findBy({ email })
    .first()
    .then((user) => {
      if (user && bcrypt.compareSync(password, user.password)) {
        // sign token
        const token = signToken(user); // new line

        // send the token
        res.status(200).json({
          token, // added token as part of the response sent
          message: `Welcome User ${user.email}!`,
        });
      } else {
        res.status(401).json({ message: "Invalid Credentials" });
      }
    })
    .catch((error) => {
      res.status(500).json(error);
    });
});

// this functions creates and signs the token
function signToken(user) {
  const payload = {
    email: user.email,
  };

  const secret = process.env.JWT_SECRET;

  const options = {
    expiresIn: "1h",
  };

  return jwt.sign(payload, secret, options); // notice the return
}

module.exports = router;
