/*
** This file and the folder that it is in was generated by the
** Node Package dukeapi found at: https://www.npmjs.com/package/dukeapi
**
** Version: 1.0.0
** Author: David H. Isakson II
** License: MIT
** Github: https://github.com/ikeman32/duke-api-wauth
** Contact: david.isakson.ii@gmail.com
*/

/*
**Contributors:
**Seth Cox
**David Isakson
**April - May 2020
*/
// IMPORTS of individual routers
const authRouter = require("../auth/auth-router.js");
const aslRouter = require("../asl/asl-router.js");
const level1Router = require("../Levels/level1-router.js");
const level2Router = require("../Levels/level2-router.js");
const level3Router = require("../Levels/level3-router.js");
const level4Router = require("../Levels/level4-router.js");
const level5Router = require("../Levels/level5-router.js");

/*
Add this to the protected routes that require a user to be logged in.
example: server.user("api/level_1", restricted, level1Router);
*/
const restricted = require("../middleware/restricted");

/*
This file contains all the routes to the endpoints and is imported into
the server.js file in the api folder. Individual routers are routed through
here in order to keep a central location for the routes and prevent the api
server file from getting cluttered as new endpoints and routers are added.
*/
module.exports = server => {
  server.use("/api/auth", authRouter);
  server.use("/api/asl", aslRouter);
  server.use("/api/level_1", level1Router);
  server.use("/api/level_2", level2Router);
  server.use("/api/level_3", level3Router);
  server.use("/api/level_4", level4Router);
  server.use("/api/level_5", level5Router);
};
